{application,lgh_phoscon_provider,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{lgh_phoscon_provider_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[lgh_phoscon_provider,lgh_phoscon_provider_app,
                        lgh_phoscon_provider_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
